
examples: spiral.c pendulum.c
	gcc spiral.c -g -lido -lm -lncurses -o spiral -L/usr/include/libido -pthread -Wall
	gcc pendulum.c -g -lido -lm -o pendulum -L/usr/include/libido -pthread -lncurses -Wall
