
examples: spiral.c pendulum.c spiralDDA.c
	gcc spiral.c -g -lido -o spiral -Wall -L/usr/include/libido -lm -lncurses -pthread
	gcc spiralDDA.c -g -lido -o spiralDDA -Wall -L/usr/include/libido -lm -lncurses -pthread
	#gcc pendulum.c -g -lido -lm -o pendulum -L/usr/include/libido -pthread -lncurses -Wall
